# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensorvalues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorvalues',
            old_name='sensorvalues',
            new_name='tem_value',
        ),
    ]
