# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensorvalues', '0006_sensorvalues_water_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorvalues',
            name='water_value',
        ),
    ]
