# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorvalues', '0009_auto_20171011_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem_value', models.CharField(max_length=250)),
                ('hum_value', models.CharField(max_length=250)),
                ('moisture', models.CharField(max_length=250)),
                ('ult_value', models.CharField(max_length=250)),
                ('rain_value', models.CharField(max_length=250)),
                ('year_value', models.CharField(max_length=250)),
                ('month_value', models.CharField(max_length=250)),
                ('day_value', models.CharField(max_length=250)),
                ('hour_value', models.CharField(max_length=250)),
                ('minute_value', models.CharField(max_length=250)),
            ],
        ),
    ]
