# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensorvalues', '0010_plant_2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sensorvalues',
            new_name='Plant_1',
        ),
    ]
