# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensorvalues', '0012_auto_20171102_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='plantid',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('plantname', models.CharField(max_length=25, null=True)),
                ('latitude', models.CharField(max_length=10, null=True)),
                ('longitude', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=250)),
                ('humidity', models.CharField(max_length=250)),
                ('waterlevel', models.CharField(max_length=250)),
                ('rain', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Plant_1',
        ),
        migrations.DeleteModel(
            name='Plant_2',
        ),
        migrations.AddField(
            model_name='plant',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensorvalues.plantid'),
        ),
    ]
