# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorvalues', '0013_auto_20171109_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='ph',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='day',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='hour',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='minute',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='month',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
