# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensorvalues', '0014_auto_20171114_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantid',
            name='plantname',
        ),
    ]
